#!/usr/bin/env bash
# -------------------------------------------------
# run_agents.sh – launch two parallel agent watchers
# -------------------------------------------------
# This script starts two background processes that watch the
# task files generated by delegate_todo.sh and run a custom
# command for each agent. Adjust the COMMAND_* variables to
# point at the actual work each agent should perform.

BASE="/home/cyserman/Projects/casecraft-premium (1)"
AGENT1_FILE="${BASE}/todo_agent_1.md"
AGENT2_FILE="${BASE}/todo_agent_2.md"

# -----------------------------------------------------------------
# Define the command each agent should run when its task file changes.
# For demonstration we simply echo a message, but you can replace
# the echo with any build script, test runner, or custom node script.
# -----------------------------------------------------------------
COMMAND_AGENT1="echo \"[Agent 1] Detected change in ${AGENT1_FILE}. Run UI/UX workflow...\""
COMMAND_AGENT2="echo \"[Agent 2] Detected change in ${AGENT2_FILE}. Run backend workflow...\""

# Helper to start a watcher using inotifywait (installed on most Linux).
watch_agent() {
  local file="$1"
  local cmd="$2"
  local name="$3"
  echo "🔎 Starting watcher for ${name} – ${file}"
  # Run in background so both watchers run concurrently.
  while true; do
    # Wait for any modify event on the file.
    inotifywait -e modify "$file" >/dev/null 2>&1
    # Execute the command.
    eval "$cmd"
  done &
}

# Ensure inotifywait is available.
if ! command -v inotifywait >/dev/null 2>&1; then
  echo "❌ inotifywait not found. Install it (e.g., sudo apt-get install inotify-tools) and rerun this script."
  exit 1
fi

# Start both watchers.
watch_agent "$AGENT1_FILE" "$COMMAND_AGENT1" "Agent 1"
watch_agent "$AGENT2_FILE" "$COMMAND_AGENT2" "Agent 2"

# Keep the script alive while background jobs run.
# Press Ctrl+C to stop both watchers.
wait
